name: Docker

on:
  push:
  schedule:
    - cron: "00 23 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build the Docker image
        run: |
          echo "目录$PWD"
          find /home -name "Dockerfile"