name: Docker

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  schedule:
    - cron: "00 23 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build the Docker image
        run: |
          echo "目录$PWD"
          ls
          docker version
          # 登录阿里云镜像仓库
          docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }} registry.cn-hangzhou.aliyuncs.com
          # 使用Dockerfile构建镜像
          docker build . --file Dockerfile --tag registry.cn-hangzhou.aliyuncs.com/dqyt/tooldelta:latest
          # 推送镜像到镜像仓库
          docker push registry.cn-hangzhou.aliyuncs.com/dqyt/tooldelta:latest